### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by leobalter** [Amorelandra/capitalism#3]
I tried to run a global install of capitalism and now the world is at war. Also, all my financials got a higher interest.

```
npm install -g capitalism
```

Does it work better if we use a decentralized / federated package registry?

**Comment by Amorelandra** [comment]
I'm sorry @leobalter, but... _entropy_ is just the natural state of the world.

This has nothing to do with capitalism.

I'm certainly open to exploring the... _opportunities_ that exist within decentralization, but I'm concerned that this could have the potential of cannibalizing our revenue.
