### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LOLdevelopr** [Amorelandra/capitalism#6]
Tried `$ npx capitalism`
But it failed
Err
```bash
Cannot find module 'H:\nothing\its-nothing-really\why-are-you-so-worried-about-it\you-will-be-hearing-from\my-lawyers'
```
And please dont tell me that this is how it suppose to run 😁

**Comment by Amorelandra** [comment]
That's strange. It works on my machine!

**Comment by LOLdevelopr** [comment]
Is this the same code pushed to the package ? (I guess it is but asked cause I couldnt locate the repo in npm page)

it seems the problem is in this line https://github.com/Amorelandra/capitalism/blob/d039ff4c54e10d0eccabb4cc1a522e3fad623289/index.js#L4

**just change the `process.cwd()` to `__dirname`**
` process.cwd() ` will return the directory from where the command is running but the ` __dirname ` will return the directory where the this code is residing that is in our global npm directory. 

Thanks!

**Comment by Amorelandra** [comment]
@LOLdevelopr ah hah! I had a suspicion, but was too sleepy last night to check it out on my Windows install.

I'll get it fixed, but only because you've done all of the work for me and now I can very easily swoop in and claim all of the credit.

Cheers!

**Comment by LOLdevelopr** [comment]
***idk when you **macOS** guys will take **windows** seriously 😁 !!***

>  but only because you've done all of the work for me and now I can very easily swoop in and claim all of the credit. 

:point_up: capitalism ? :no_mouth: 

waiting for next release then  :beers:

**Comment by Amorelandra** [comment]
@LOLdevelopr please see version 5.0.1 and let me know if all of my hard work fixes your problem!

**Comment by LOLdevelopr** [comment]
It should be in `index.js` 😶
Still same prob

**Comment by Amorelandra** [comment]
Fixed!
